### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/Cards-Rob#1]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- Muy buen trabajo @Roberttovarv . Felicitaciones 🥳
## Estilo de código y limpieza
- ¡Buen trabajo!
## Mejores prácticas/comentarios
- Te invito a que implementes estos extras 
![Captura de pantalla de 2024-04-08 11-30-15](https://github.com/4GeeksAcademy/Cards-Rob/assets/139759297/16299447-fb0b-4aa4-b120-cf4debf7c0b1)

**Comment by Roberttovarv** [comment]
Gracias Eduardo,

Con futuros eventos intentaré hacer los adicionales a disposición de mi tiempo! :)
